server.port=8081
spring.application.name=order-producer-service

# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092

# Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis Config
spring.redis.host=localhost
spring.redis.port=6379